apiVersion: apps/v1
kind: Deployment
metadata:
  name: chinchilla-site
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chinchilla-site
  template:
    metadata:
      labels:
        app: chinchilla-site
    spec:
      containers:
      - name: chinchilla-site
        image: 915776808314.dkr.ecr.us-east-1.amazonaws.com/cloudproject:latest
        ports:
        - containerPort: 8000
        env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: SECRET_KEY
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: DB_PASSWORD
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: DB_PORT
        # Resource Limits
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        # Health Checks
        livenessProbe:
          httpGet:
            path: /                
            port: 80               
          initialDelaySeconds: 15  
          periodSeconds: 10     
        readinessProbe:
          httpGet:
            path: /               
            port: 80               
          initialDelaySeconds: 5   
          periodSeconds: 5     