apiVersion: apps/v1
kind: Deployment
metadata:
  name: chinchilla-site
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chinchilla-site
  template:
    metadata:
      labels:
        app: chinchilla-site
    spec:
      serviceAccountName: default  
      containers:
      - name: chinchilla-site
        image: 915776808314.dkr.ecr.us-east-1.amazonaws.com/cloudproject:latest
        ports:
        - containerPort: 8000
        env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: aws-secrets
              key: SECRET_KEY
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: aws-secrets
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: aws-secrets
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: aws-secrets
              key: DB_PASSWORD
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: aws-secrets
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: aws-secrets
              key: DB_PORT
        - name: ALLOWED_HOSTS
          value: "a00047a36485a44a6935875713745ed9-1778033245.us-east-1.elb.amazonaws.com"
        command: ["sh", "-c", "printenv | grep ALLOWED_HOSTS && python manage.py runserver 0.0.0.0:8000"]
        # resource limiters
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        health checks
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "aws-secrets"