apiVersion: v1
kind: Service
metadata:
  name: chinchilla-site-service
spec:
  selector:
    app: chinchilla-site
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
