name: Docker Image Building

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  IMG_NAME: 'chinchilla-site'
  USERNAME: "justtyna22"

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set App Name
        run: 'echo "IMG_NAME=$(echo ${USERNAME})/$(echo ${IMG_NAME})" >> $GITHUB_ENV'

      - name: Login to Docker Account
        uses: docker/login-action@v1
        with:
          username: ${{ env.USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: justtyna22/chinchilla-site:latest
      